# Let us see if Linear regression can learn to predict the next fibonacci number given just the previous fib number (1D input)

In [ ]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [ ]:
X = np.array([0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610])
y = np.array([1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987])
X,y

(array([  0,   1,   1,   2,   3,   5,   8,  13,  21,  34,  55,  89, 144,
        233, 377, 610]),
 array([  1,   1,   2,   3,   5,   8,  13,  21,  34,  55,  89, 144, 233,
        377, 610, 987]))

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25,shuffle=True)
X_train = X_train.reshape(-1, 1)
X_test = X_test.reshape(-1, 1)

regr = LinearRegression()

regr.fit(X_train, y_train)
print(regr.score(X_test, y_test))

0.9999561540000893


In [ ]:
test = np.array([10946]).reshape(-1,1)
regr.predict(test)

array([17707.39277275])

In [ ]:
test = np.array([317811]).reshape(-1,1)
regr.predict(test)

array([514120.43599196])

First 100 terms of Fibonacci series are :- 0 1 1 2 3 5 8 13 21 34 55 89 144 233 377 610 987 1597 2584 4181 6765 10946 17711 28657 46368 75025 121393 196418 317811 514229 832040 1346269 2178309 3524578 5702887 9227465 14930352 24157817 39088169 63245986 102334155 165580141 267914296 433494437 701408733 1134903170

# Let's try with 2D input. The model should be able to learn this linear relationship - and predict the next fib number given the previous 2 fib numbers.

In [ ]:
X1 = np.array([0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610])
X2 = np.array([1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987])
X = np.vstack((X1,X2))
y = np.array([1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597])

In [ ]:
X

array([[  0,   1,   1,   2,   3,   5,   8,  13,  21,  34,  55,  89, 144,
        233, 377, 610],
       [  1,   1,   2,   3,   5,   8,  13,  21,  34,  55,  89, 144, 233,
        377, 610, 987]])

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X.T, y, test_size = 0.25,shuffle=True)
regr = LinearRegression()

regr.fit(X_train, y_train)
print(regr.score(X_test, y_test))

1.0


In [ ]:
test = np.array([196418,317811]).reshape(1,2)
regr.predict(test) # expected: 514229

array([514229.])

In [ ]:
test = np.array([102334155,165580141]).reshape(1,2)
regr.predict(test).astype(int) # expected: 267914296

array([267914296])

In [ ]:
test = np.array([433494437,701408733]).reshape(1,2)
regr.predict(test).astype(int) # expected: 1134903170

array([1134903170])

In [ ]:
test = np.array([27777890035288,44945570212853]).reshape(1,2)
regr.predict(test).astype(int) # expected: 72723460248141

array([72723460248141])

int64 supports upto 19 digits. Try even larger numbers. [List of Fibonacci Numbers - LINK.](https://blog.abelotech.com/posts/first-500-fibonacci-numbers/)